language: java
sudo: false
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  -  $HOME/.m2

